### ISSUE TITLE
Texto com acento no combobox não são "filtráveis"

### ISSUE THREAD

**Issue by rogeriomq** [jesuino/javafx-combox-autocomplete#1]
Por exemplo, caso eu digite: pérsia, o filtro não funcionaria, logo é preciso uma função que antes de realizar a comparação com o texto informado com os toStrings do comboBox, fizesse a retirada dos acentos no momento da comparação. Potencializando a filtragem.

**Comment by jesuino** [comment]
Obrigado :+1: acabei de fazer o teste com o código que você sugeriu, ficou legal!

**Comment by rogeriomq** [comment]
Agora quanto ao espaço.. por exemplo, no caso de um comboBox para cidades, tem que nome composto, o filtro também ficaria com restrições já que no keypress ESCAPE o popup do combo fecha. Tentarei com ele editável e propagar as ações de Keys no textfield do combobox...
